//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageServiceProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GarageServiceProxy.Captain))]
    public partial class User : GarageServiceProxy.BaseEntity
    {
        
        private int GroupNumberField;
        
        private string PasswordField;
        
        private GarageServiceProxy.PaymentMethod PaymentMethodField;
        
        private string UniqueCodeField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupNumber
        {
            get
            {
                return this.GroupNumberField;
            }
            set
            {
                this.GroupNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GarageServiceProxy.PaymentMethod PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueCode
        {
            get
            {
                return this.UniqueCodeField;
            }
            set
            {
                this.UniqueCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GarageServiceProxy.PaymentMethod))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GarageServiceProxy.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GarageServiceProxy.Message))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GarageServiceProxy.Transaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GarageServiceProxy.User))]
    public partial class BaseEntity : object
    {
        
        private int IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentMethod", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class PaymentMethod : GarageServiceProxy.BaseEntity
    {
        
        private string CardNumberField;
        
        private string CardholderNameField;
        
        private int CvcField;
        
        private System.DateTime ExpiryField;
        
        private int UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardholderName
        {
            get
            {
                return this.CardholderNameField;
            }
            set
            {
                this.CardholderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cvc
        {
            get
            {
                return this.CvcField;
            }
            set
            {
                this.CvcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Expiry
        {
            get
            {
                return this.ExpiryField;
            }
            set
            {
                this.ExpiryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Product : GarageServiceProxy.BaseEntity
    {
        
        private bool AvailabilityField;
        
        private GarageServiceProxy.ItemCategory CategoryField;
        
        private GarageServiceProxy.ItemCondition ConditionField;
        
        private System.DateTime DatePostedField;
        
        private string DescriptionField;
        
        private byte[] ImageField;
        
        private string NameField;
        
        private GarageServiceProxy.Captain OwnerField;
        
        private double PriceField;
        
        private bool RequestField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Availability
        {
            get
            {
                return this.AvailabilityField;
            }
            set
            {
                this.AvailabilityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GarageServiceProxy.ItemCategory Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GarageServiceProxy.ItemCondition Condition
        {
            get
            {
                return this.ConditionField;
            }
            set
            {
                this.ConditionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatePosted
        {
            get
            {
                return this.DatePostedField;
            }
            set
            {
                this.DatePostedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GarageServiceProxy.Captain Owner
        {
            get
            {
                return this.OwnerField;
            }
            set
            {
                this.OwnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Request
        {
            get
            {
                return this.RequestField;
            }
            set
            {
                this.RequestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Message : GarageServiceProxy.BaseEntity
    {
        
        private string ContentField;
        
        private GarageServiceProxy.Product ProductField;
        
        private GarageServiceProxy.Captain ReceiverField;
        
        private GarageServiceProxy.Captain SenderField;
        
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GarageServiceProxy.Product Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GarageServiceProxy.Captain Receiver
        {
            get
            {
                return this.ReceiverField;
            }
            set
            {
                this.ReceiverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GarageServiceProxy.Captain Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Transaction : GarageServiceProxy.BaseEntity
    {
        
        private GarageServiceProxy.User BuyerField;
        
        private GarageServiceProxy.Product ProductField;
        
        private GarageServiceProxy.User SellerField;
        
        private GarageServiceProxy.OrderStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GarageServiceProxy.User Buyer
        {
            get
            {
                return this.BuyerField;
            }
            set
            {
                this.BuyerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GarageServiceProxy.Product Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GarageServiceProxy.User Seller
        {
            get
            {
                return this.SellerField;
            }
            set
            {
                this.SellerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GarageServiceProxy.OrderStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Captain", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Captain : GarageServiceProxy.User
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemCategory", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public enum ItemCategory : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mechanics = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Electronics = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Programming = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Engines = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manufacturing = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemCondition", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public enum ItemCondition : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LikeNew = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VeryGood = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Good = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Acceptable = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Refurbished = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatus", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public enum OrderStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Confirmed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Shipped = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivered = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GarageServiceProxy.IGarageService")]
    public interface IGarageService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Login", ReplyAction="http://tempuri.org/IUserService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, int groupnumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SelectAllUsers", ReplyAction="http://tempuri.org/IUserService/SelectAllUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GarageServiceProxy.User>> SelectAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SelectUserByID", ReplyAction="http://tempuri.org/IUserService/SelectUserByIDResponse")]
        System.Threading.Tasks.Task<GarageServiceProxy.User> SelectUserByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/SelectAllPaymentMethods", ReplyAction="http://tempuri.org/IPaymentService/SelectAllPaymentMethodsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GarageServiceProxy.PaymentMethod>> SelectAllPaymentMethodsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/SelectPaymentMethodByID", ReplyAction="http://tempuri.org/IPaymentService/SelectPaymentMethodByIDResponse")]
        System.Threading.Tasks.Task<GarageServiceProxy.PaymentMethod> SelectPaymentMethodByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/SelectAllProducts", ReplyAction="http://tempuri.org/IProductService/SelectAllProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GarageServiceProxy.Product>> SelectAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/SelectProductByID", ReplyAction="http://tempuri.org/IProductService/SelectProductByIDResponse")]
        System.Threading.Tasks.Task<GarageServiceProxy.Product> SelectProductByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/SelectAllMessages", ReplyAction="http://tempuri.org/IMessageService/SelectAllMessagesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GarageServiceProxy.Message>> SelectAllMessagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/SelectMessageByID", ReplyAction="http://tempuri.org/IMessageService/SelectMessageByIDResponse")]
        System.Threading.Tasks.Task<GarageServiceProxy.Message> SelectMessageByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransacionService/SelectAllPaymentMethod", ReplyAction="http://tempuri.org/ITransacionService/SelectAllPaymentMethodResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GarageServiceProxy.Transaction>> SelectAllPaymentMethodAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransacionService/SelectTransactionByID", ReplyAction="http://tempuri.org/ITransacionService/SelectTransactionByIDResponse")]
        System.Threading.Tasks.Task<GarageServiceProxy.Transaction> SelectTransactionByIDAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IGarageServiceChannel : GarageServiceProxy.IGarageService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class GarageServiceClient : System.ServiceModel.ClientBase<GarageServiceProxy.IGarageService>, GarageServiceProxy.IGarageService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GarageServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(GarageServiceClient.GetBindingForEndpoint(endpointConfiguration), GarageServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GarageServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GarageServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GarageServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GarageServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GarageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, int groupnumber, string password)
        {
            return base.Channel.LoginAsync(username, groupnumber, password);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GarageServiceProxy.User>> SelectAllUsersAsync()
        {
            return base.Channel.SelectAllUsersAsync();
        }
        
        public System.Threading.Tasks.Task<GarageServiceProxy.User> SelectUserByIDAsync(int id)
        {
            return base.Channel.SelectUserByIDAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GarageServiceProxy.PaymentMethod>> SelectAllPaymentMethodsAsync()
        {
            return base.Channel.SelectAllPaymentMethodsAsync();
        }
        
        public System.Threading.Tasks.Task<GarageServiceProxy.PaymentMethod> SelectPaymentMethodByIDAsync(int id)
        {
            return base.Channel.SelectPaymentMethodByIDAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GarageServiceProxy.Product>> SelectAllProductsAsync()
        {
            return base.Channel.SelectAllProductsAsync();
        }
        
        public System.Threading.Tasks.Task<GarageServiceProxy.Product> SelectProductByIDAsync(int id)
        {
            return base.Channel.SelectProductByIDAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GarageServiceProxy.Message>> SelectAllMessagesAsync()
        {
            return base.Channel.SelectAllMessagesAsync();
        }
        
        public System.Threading.Tasks.Task<GarageServiceProxy.Message> SelectMessageByIDAsync(int id)
        {
            return base.Channel.SelectMessageByIDAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GarageServiceProxy.Transaction>> SelectAllPaymentMethodAsync()
        {
            return base.Channel.SelectAllPaymentMethodAsync();
        }
        
        public System.Threading.Tasks.Task<GarageServiceProxy.Transaction> SelectTransactionByIDAsync(int id)
        {
            return base.Channel.SelectTransactionByIDAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGarageService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IGarageService))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGarageService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5000/GarageService/basichttp");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IGarageService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:5001/GarageService/WSHttps");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IGarageService,
            
            WSHttpBinding_IGarageService,
        }
    }
}
